#!/usr/bin/env bash
#install nginx and create index.html file with Hello World text

#!/usr/bin/env bash
# Push from client a file
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
/etc/init.d/nginx start
