#!/usr/bin/env bash
# allow Nginx to connect through port 80
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
html="<h1>Hello World</h1>"
echo "$html" > /var/www/html/index.nginx-debian.html
