#!/usr/bin/env bash
#install nginx and create index.html file with Hello World text

#!/usr/bin/env bash
# Push from client a file
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx start
