#!/usr/bin/env bash
#install ngix and put shcool inside
# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Configure the redirection in Nginx
cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
EOF

# Restart Nginx
service nginx restart
