#!/usr/bin/env bash
# A script that displays "Best School" 10 time, but displays "Hi" at the 9th line

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
