#!/usr/bin/env bash
# A script that displays "Best School" ten times, "bad luck" as 4th and "Good luck" as 8th

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
		((i++))
done


