#!/usr/bin/env bash
# The content of the current directory
# only display the part of the name after the first dash is displayed (refer to the example)

l=$(ls)
for i in $l; do
	echo "$i" | cut -d '' -f2
done
